apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timer-getter-project-a
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/reverendyz/argo-test.git
        revision: fix/encryption-keys-to-new-host #HEAD
        files:
          - path: argocd/projects/project-a/project.yaml
  template:
    metadata:
      name: '{{project}}-app'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/reverendyz/argo-test.git
          targetRevision: fix/encryption-keys-to-new-host #HEAD
          ref: valuesRef
        - repoURL: https://github.com/reverendyz/helm-charts.git
          targetRevision: feature/improvements-timer-api-templates
          path: sample-service/timer-api
          helm:
            valueFiles:
              - "$valuesRef/argocd/projects/{{project}}/defaults/values.yaml"
              - "$valuesRef/argocd/projects/{{project}}/overrides/values.yaml"
        - repoURL: https://github.com/reverendyz/argo-test.git
          targetRevision: fix/encryption-keys-to-new-host #HEAD
          path: argocd/projects/{{project}}/overrides/sealedsecrets
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
