replicaCount: 3

namespace: app-project-a

image:
  tag: latest

secrets:
  - volumeName: private-key
    secretName: jwt-private-key
    key: pri
    fileName: pri
  - volumeName: public-key
    secretName: jwt-public-key
    key: pub
    fileName: pub

imagePullSecrets:
  - dockerhub-secret

service:
  type: NodePort
  targetPort: 8080
