apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/reverendyz/argo-test.git
        revision: feat/update-secrets #HEAD
        files:
          - path: argocd/projects/observability/project.yaml
  template:
    metadata:
      name: '{{project}}-prometheus'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/reverendyz/argo-test.git
          targetRevision: feat/update-secrets #HEAD
          ref: valuesRef
        - repoURL: https://github.com/reverendyz/helm-charts.git
          targetRevision: HEAD
          path: sample-service/observability
          helm:
            valueFiles:
              - "$valuesRef/argocd/projects/{{project}}/defaults/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

           